### ISSUE TITLE
Numpy version

### ISSUE THREAD

**Issue by josemunozc** [wtsi-hgi/indelible-docker#1]
Hi,

After building Indelible using Docker I found the following error message when running `indelible.py --help`:

`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

I think this might be related to Numpy version being installed:
```
RUN pip install numpy Cython
RUN pip install -r requirements.txt
```

I think the first line tries to install the latest Numpy version but then requirements specify version 1.17.2 and pip tries to roll back. Seems to go fine until I tried printing the help message which gave the error message above. I got it to work by changing:
```
RUN pip install 'numpy==1.17.2' Cython
RUN pip install -r requirements.txt
```

**Comment by eugenegardner** [comment]
@gn5 – I have modified the requirements.txt file to reflect the correct numpy version that keeps this warning from being thrown.

**Comment by gn5** [comment]
Thank you for reporting this. I have adjusted the Dockerfile as suggested to build numpy version 1.17.2.
It's in docker hub at `mercury/indelible:hg19_feb0a6f`
